config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants, only: [:index, :show]
  resources :categories, only: :show
  root "restaurants#index"


  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :restaurants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name,:tel,:address,:opening_hours,:description
  mount_uploader :image, PhotoUploader
  belongs_to :category, optional: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         def admin?
           self.role == "admin"
         end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    before_action :authenticate_admin

    private

     def authenticate_admin
       unless current_user.admin?
         flash[:alert] = "Not allow!"
         redirect_to root_path
       end
     end
  end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    if params[:id]
      set_category
    else
      @category = Category.new
    end
  end

def create
  @category = Category.new(category_params)
  if @category.save
    flash[:notice] = "創建成功"
    redirect_to admin_categories_path
  else
    @categories = Category.all
    render :index
  end
end

def update
  set_category
  if @category.update(category_params)
    redirect_to admin_categories_path
    flash[:notice] = "category was successfully updated"
  else
    @categories = Category.all
    render :index
  end
end

def destroy
   set_category
   @category.destroy
   flash[:alert] = "category was successfully deleted"
   redirect_to admin_categories_path
 end

private

def set_category
  @category = Category.find(params[:id])
end

def category_params
  params.require(:category).permit(:name)
end



end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
  @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
     @restaurant = Restaurant.new
   end

   def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end


 def show
 end

 def edit
 end

 def update
   if @restaurant.update(restaurant_params)
     redirect_to admin_restaurant_path(@restaurant)
     flash[:notice] = "restaurant was successfully updated"
   else
     render :edit
     flash[:alert] = "restaurant was failed to update"
   end
 end

 def destroy
 @restaurant.destroy
redirect_to admin_restaurants_path
flash[:alert] = "restaurant was deleted"
end



  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :authenticate_user!
  private

  def authenticate_admin
   unless current_user.admin?
     flash[:alert] = "Not allow!"
     redirect_to root_path
   end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
  @categories = Category.all
  @category = Category.find(params[:id])
  @restaurants = @category.restaurants.page(params[:page]).per(9)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all     # 加上這一行
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>
  <br>
  <div class="form-inline" >
    <%= form_for [:admin, @category] do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
    <% if @category.errors.any? %>
      <%= @category.errors.full_messages.to_sentence %>
    <% end %>
  </div>


  <br>
  <div>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>
  <br>
  <div class="row">

    <div class="col-md-12">

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>

          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td>  <%= link_to 'Edit', admin_categories_path(id: category.id) %>
            <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/admin/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
<h2>We have some errors here !</h2>
<ul>
  <% @restaurant.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
<%= f.label :category, "category" %><br>
<%= f.collection_select :category_id, Category.all, :id, :name, {}, {} %><br>
<br>

<%= f.label :name, "Name" %><br>
<%= f.text_field :name %><br>
<br>
  <%= f.label :tel, "Tel" %><br>
  <%= f.text_field :tel %><br>
<br>
  <%= f.label :address, "Address" %><br>
  <%= f.text_field :address %><br>
<br>
  <%= f.label :opening_hours, "Opening Hours" %><br>
  <%= f.text_field :opening_hours %><br>
<br>
  <%= f.label :description, "Description" %><br>
  <%= f.text_area :description %><br>

<br>
  <%= f.label :image, "Photo" %>
  <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
  <%= f.file_field :image %>
<br>
<%= f.submit %>
<br>
<br>


<%= link_to 'Back to index', admin_restaurants_path %>

<% end %>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">
  <h1>餐廳後台</h1>
  <div class="row">
     <div class="col-md-12">
      <div>
        <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
      </div><br>
          <div>
            <%= link_to 'Restaurant', admin_restaurants_path %> |
            <%= link_to 'Categories', admin_categories_path %>
          </div><br>
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                <th>#</th>
                <th>Category</th>
                <th>Name</th>
                </tr>
              </thead>
                  <tbody>
                    <% @restaurants.each do |restaurant| %>
                      <tr>
                      <th scope="row"><%= restaurant.id %></th>
                      <td>[<%= restaurant.category.name %>]</td>
                      <td><%= restaurant.name %></td>
                      </tr>
                      <td>
                      <%= link_to 'Show', admin_restaurant_path(restaurant) %>
                      <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
                      <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
                      </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
          </div>
      <div class="text-center">
       <%= paginate @restaurants %>
      </div>
    </div>
  </div>
</div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
<h2>We have some errors here !</h2>
<ul>
  <% @restaurant.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>


<% end %>

app/views/admin/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

Opening Hours:<%= @restaurant.opening_hours %><br>
Tel: <%= @restaurant.tel %><br>
Address: <%= @restaurant.address %><br>
Description:<%= @restaurant.description %><br>
<%= @restaurant.category.name %>
<br/>

<%= link_to 'Back to index', admin_restaurants_path %>
<%= image_tag @restaurant.image, width: '600px' %>

app/views/categories/show.html.erb
<h1>餐廳介紹</h1><br>
<div class="container">
  <div class="row">
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation">
        <%= link_to "全部餐廳", root_path %>
      </li>
      <% @categories.each do |category| %>
        <li role="presentation" class="<%= "active" if category == @category %>">
          <%= link_to category.name, category_path(category) %>
        </li>
      <% end %>
    </ul>
    <br>
    <%= render partial: "shared/restaurant_list" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- 導覽列 -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
              <% end %>
            <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
            <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <!-- 登入訊息
      <% if flash[:alert] %>
      <div class="container">
        <div class="row">
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= alert %>
          </div>
        </div>
      </div>
      <% end %>
  -->
  
    <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>



    <%= yield %>

  </body>
</html>

app/views/restaurants/index.html.erb
<h1>餐廳介紹</h1><br>
<div class="container">
  <div class="row">
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
    <br>
    <%= render partial: "shared/restaurant_list" %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
    </div>

    <div class="clearfix"></div>

    <hr>

  </div>
</div>

app/views/shared/_restaurant_list.html.erb
<% fake_img_value=1 %>
<% @restaurants.each do |restaurant| %>
<div class="col-sm-6 col-md-4">
  <div class="restaurant-item">
    <%= image_tag restaurant.image, class: "img-responsive center-block" %>
    <%= image_tag("http://lorempixel.com/300/300/food/" + fake_img_value.to_s) %>
      <% fake_img_value+=1 %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %><p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
      </div>
    </div>
  </div>
<% end %>
<div class="text-center">
  <%= paginate @restaurants %>
</div>